Реализовал работу видеоплеера
htmlacademy-react/892619-what-to-watch-5 pull request #12
Opened 2020-11-12 12:50 UTC by Egrik-Dev

2020-11-14 09:05 UTC, chechenev requested changes

2020-11-14 09:05 UTC, chechenev commented on src/components/player/player.jsx
> +  const activeFilmId = Number(window.location.pathname.substring(QUANTITY_RENDERED_FILMS));
Можно обойтись без такой конструкции, а получать данные из `Route`.

Например, `props.match.params.id`

или Route сделать чуть иначе и явно передать пропсы, используя метод `render`:

```
<Route exact path="/player/:id" render={(props)=>{
    <PlayerScreen id={props.match.params.id} films={films}/>
}} />
```

2020-11-15 19:38 UTC, Egrik-Dev commented on src/components/player/player.jsx
> +  const activeFilmId = Number(window.location.pathname.substring(QUANTITY_RENDERED_FILMS));
Классно) А я велосипед до этого изобретал чтоб id получить

2020-11-16 08:47 UTC, chechenev approved these changes

2020-11-16 08:47 UTC, merged